-- Run through the Supabase SQL connector. All fixture writes roll back.
begin;
select set_config('request.jwt.claim.sub',(select user_id::text from public.platform_admins order by created_at limit 1),true);
set local role authenticated;
do $test$
declare v_org uuid; v_venue uuid; v_second uuid; v_rows jsonb; v_result jsonb; v_failed boolean; v_slot text;
begin
  v_org := public.create_organization('Import verification','import-verification-' || substr(gen_random_uuid()::text,1,8),null);
  perform set_config('import_test.org',v_org::text,true);
  v_venue := public.create_venue(v_org,'First venue','first-venue','America/Chicago','USD','US',null,null,null,null,'restaurant');
  perform set_config('import_test.venue',v_venue::text,true);
  v_second := public.create_venue(v_org,'Second venue','second-venue','America/Chicago','USD','US',null,null,null,null,'restaurant');
  v_rows := '[{"sku":"TEST-ITEM","name":"Paper cups","unit_cost":"1.2500"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'inventory',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: inventory %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'inventory',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: inventory %',v_result; end if;
  v_rows := '[{"sku":"TEST-WINE","producer":"Test winery","cuvee":"Reserve","wine_type":"red","vintage":"2024","bottle_ml":"750","unit_cost":"12.5"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'wines',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: wines %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'wines',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: wines %',v_result; end if;
  v_rows := '[{"code":"CON","name":"North concourse","kind":"concourse"},{"code":"OUT","name":"North outlet","kind":"outlet","parent_code":"CON"},{"code":"ROOM","name":"Reserve room","kind":"room","parent_code":"OUT"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'locations',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: locations %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'locations',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: locations %',v_result; end if;
  v_rows := '[{"location_code":"ROOM","code":"RACK","name":"North rack","template_key":"bin_rack"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'racks',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: racks %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'racks',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: racks %',v_result; end if;
  v_rows := '[{"name":"Test supplier","email":"test@example.com","lead_time_days":"2"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'suppliers',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: suppliers %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'suppliers',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: suppliers %',v_result; end if;
  v_rows := '[{"external_id":"receipt-1","sku":"TEST-ITEM","supplier":"Test supplier","quantity":"6","unit_cost":"1.25"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'stock',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: stock %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'stock',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: stock %',v_result; end if;
  v_rows := '[{"label":"T1","capacity":"4"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'tables',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: tables %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'tables',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: tables %',v_result; end if;
  v_rows := '[{"external_id":"guest-1","name":"Test guest","vip":"false"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'guests',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: guests %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'guests',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: guests %',v_result; end if;
  v_rows := '[{"external_id":"booking-1","guest_external_id":"guest-1","party_size":"2","reserved_at":"2026-10-01T19:00:00-05:00"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'reservations',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: reservations %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'reservations',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: reservations %',v_result; end if;
  v_rows := '[{"external_id":"member-1","name":"Test member","tier":"standard"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'members',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: members %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'members',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: members %',v_result; end if;
  v_rows := '[{"external_id":"event-1","name":"Test event","guest_count":"20","starts_at":"2026-10-02T18:00:00-05:00"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'events',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: events %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'events',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: events %',v_result; end if;
  v_rows := '[{"external_id":"shift-1","role_key":"host","starts_at":"2026-10-01T17:00:00Z","ends_at":"2026-10-01T22:00:00Z"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'shifts',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: shifts %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'shifts',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: shifts %',v_result; end if;
  v_rows := '[{"name":"Opening checklist","item_label":"Check cooler"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'checklists',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: checklists %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'checklists',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: checklists %',v_result; end if;
  v_rows := '[{"external_id":"doc-1","title":"Opening procedure","body":"Check inventory before opening."}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'documents',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: documents %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'documents',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: documents %',v_result; end if;
  v_rows := '[{"name":"Dinner list","kind":"bottle","threshold":"2"}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'wine_lists',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: wine_lists %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'wine_lists',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: wine_lists %',v_result; end if;
  v_rows := '[{"list_name":"Dinner list","list_kind":"bottle","sku":"TEST-WINE","pour_ml":""}]'::jsonb;
  v_result := public.import_venue_data(v_org,v_venue,'list_items',v_rows);
  if (v_result->>'imported')::int < 1 then raise exception 'Create failed: list_items %',v_result; end if;
  v_result := public.import_venue_data(v_org,v_venue,'list_items',v_rows);
  if (v_result->>'skipped')::int <> jsonb_array_length(v_rows) then raise exception 'Replay failed: list_items %',v_result; end if;
  if (select sum(quantity) from public.inventory_balances where venue_id=v_venue and item_id=(select id from public.inventory_items where organization_id=v_org and sku='TEST-ITEM')) <> 6 then raise exception 'Stock replay changed balance'; end if;
  select location_code into v_slot from public.storage_slots where venue_id=v_venue order by location_code limit 1;
  v_rows := jsonb_build_array(jsonb_build_object('external_id','receipt-bin','sku','TEST-ITEM','supplier','Test supplier','quantity','1','unit_cost','1.25','slot_code',v_slot));
  perform public.import_venue_data(v_org,v_venue,'stock',v_rows);
  v_result := public.import_venue_data(v_org,v_venue,'stock',v_rows);
  if (v_result->>'skipped')::int <> 1 or (select sum(quantity) from public.inventory_balances where venue_id=v_venue and slot_id is not null) <> 1 then raise exception 'Bin receipt or replay failed'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'stock','[{"external_id":"rollback-receipt","sku":"TEST-ITEM","supplier":"Test supplier","quantity":"3"},{"external_id":"invalid-receipt","sku":"MISSING","supplier":"Test supplier","quantity":"3"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed or (select sum(quantity) from public.inventory_balances where venue_id=v_venue) <> 7 then raise exception 'Stock batch failed to roll back'; end if;
  v_result := public.import_venue_data(v_org,v_second,'inventory','[{"sku":"TEST-ITEM","name":"Paper cups","unit_cost":"1.2500"}]');
  if (v_result->>'skipped')::int <> 1 then raise exception 'Org-wide replay failed'; end if;
  v_result := public.import_venue_data(v_org,v_venue,'inventory','[{"sku":"TEST-ITEM","name":"Updated cups","unit_cost":"1.2500"}]');
  if (v_result->>'updated')::int <> 1 then raise exception 'Metadata update failed'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'stock','[{"external_id":"receipt-1","sku":"TEST-ITEM","supplier":"Test supplier","quantity":"7","unit_cost":"1.25"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed then raise exception 'Changed receipt accepted'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'inventory','[{"sku":"ROLLBACK-AA","name":"Valid"},{"sku":"ROLLBACK-BB","name":"Invalid","unit_cost":"-1"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed or exists(select 1 from public.inventory_items where organization_id=v_org and sku='ROLLBACK-AA') then raise exception 'Batch did not roll back'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_second,'locations','[{"code":"BAD","name":"Foreign parent","kind":"room","parent_code":"CON"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed then raise exception 'Cross venue parent accepted'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'locations','[{"code":"CON","name":"North concourse","kind":"concourse","parent_code":"ROOM"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed then raise exception 'Parent cycle accepted'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'inventory','[{"sku":"AA","name":"Unknown field","organization_id":"spoof"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed then raise exception 'Unknown field accepted'; end if;
  v_failed := false;
  begin
    perform public.import_venue_data(v_org,v_venue,'inventory','[{"sku":"DUP","name":"Duplicate"},{"sku":"dup","name":"Duplicate"}]');
  exception when sqlstate '22023' then v_failed:=true; end;
  if not v_failed then raise exception 'Duplicate source key accepted'; end if;
end;
$test$;
reset role;
delete from public.platform_admins where user_id=auth.uid();
update public.memberships set role_key='host',venue_id=current_setting('import_test.venue')::uuid where organization_id=current_setting('import_test.org')::uuid and user_id=auth.uid();
set local role authenticated;
do $negative$
declare denied boolean:=false;
begin
  begin
    perform public.import_venue_data(current_setting('import_test.org')::uuid,current_setting('import_test.venue')::uuid,'inventory','[{"sku":"DENIED","name":"Denied"}]');
  exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'Host import permission was not enforced'; end if;
  perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
  denied:=false;
  begin
    perform public.import_venue_data(current_setting('import_test.org')::uuid,current_setting('import_test.venue')::uuid,'guests','[{"external_id":"denied","name":"Denied guest"}]');
  exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'Outsider tenant access was not denied'; end if;
end;
$negative$;
rollback;
select 'PASS: all 16 datasets, metadata updates, replay protection, atomic rollback, parent isolation, cycles, field validation and permissions' as result;
