-- Workforce permissions generated from RoleCatalog.
insert into public.app_roles(key,label,rank) values
('organization_owner', 'Organization owner', 10),
('venue_administrator', 'Venue administrator', 20),
('general_manager', 'General manager', 30),
('beverage_director', 'Beverage director', 40),
('event_manager', 'Event manager', 40),
('floor_manager', 'Floor manager', 50),
('scheduler', 'Scheduler', 50),
('department_manager', 'Department manager', 45),
('shift_lead', 'Shift lead', 55),
('employee', 'Employee', 70),
('host', 'Host', 60),
('bartender', 'Bartender', 60),
('server', 'Server', 70),
('inventory_counter', 'Inventory counter', 70),
('auditor', 'Read-only auditor', 120)
on conflict(key) do update set label=excluded.label, rank=excluded.rank;
insert into public.permissions(key,description) values
('schedule.board', 'View all authorized schedules'),
('schedule.create', 'Create draft shifts'),
('schedule.edit', 'Edit draft and published shifts'),
('schedule.retract', 'Retract schedules'),
('schedule.copy', 'Copy schedules'),
('schedule.open', 'Offer open shifts'),
('schedule.requirements', 'Manage staffing requirements'),
('schedule.drop.review', 'Review shift releases'),
('schedule.pickup.review', 'Review shift pickups'),
('schedule.swap.review', 'Review shift swaps'),
('schedule.assign', 'Assign qualified staff'),
('schedule.override', 'Document availability and rest overrides'),
('labor.read', 'View wages and labor costs'),
('labor.wage.manage', 'Manage effective wage rates'),
('schedule.availability.edit', 'Edit staff availability'),
('schedule.availability.all', 'View staff availability'),
('schedule.timeoff.review', 'Review time off'),
('schedule.templates', 'Manage schedule templates'),
('schedule.report', 'View schedule and attendance reports'),
('schedule.settings', 'Manage workforce settings'),
('staff.manage', 'Manage employment and job roles'),
('staff.certify', 'Verify qualifications and certifications'),
('schedule.self', 'View personal shifts and availability'),
('schedule.marketplace', 'Request shift releases, pickups and swaps'),
('org.read', 'View the organization profile'),
('org.update', 'Update organization identity'),
('venue.create', 'Create a venue'),
('venue.read', 'View venue profile and hours'),
('venue.update', 'Update venue settings'),
('membership.read', 'View team memberships'),
('membership.invite', 'Invite a person to the organization'),
('membership.approve', 'Approve or decline a join request'),
('membership.assign_role', 'Change an existing membership role'),
('audit.read', 'Read the audit log'),
('wine.catalog.read', 'View the wine catalog'),
('wine.catalog.write', 'Edit wine master data'),
('wine.count.execute', 'Enter inventory counts'),
('wine.count.review', 'Review count variances'),
('wine.count.approve', 'Approve count adjustments'),
('wine.movement.write', 'Move or transfer inventory'),
('wine.receive', 'Receive purchase orders'),
('wine.purchase', 'Create purchase orders and manage vendors'),
('wine.cost.read', 'View unit cost and valuation'),
('wine.allocation.manage', 'Manage club allocations and member holdings'),
('wine.list.publish', 'Publish wine list availability'),
('reservation.read', 'View reservations'),
('reservation.write', 'Create and edit reservations'),
('reservation.seat', 'Seat, waitlist, and complete covers'),
('floor.read', 'View the live floor'),
('floor.design', 'Edit floor layouts'),
('guest.read', 'View guest profiles'),
('guest.write', 'Edit guest profiles and notes'),
('schedule.read', 'View the published schedule'),
('schedule.publish', 'Publish schedules'),
('timeclock.self', 'Clock in and out for yourself'),
('timeclock.manage', 'Review and correct time entries'),
('checklist.execute', 'Complete assigned checklist items'),
('checklist.manage', 'Manage checklist templates and signoff'),
('logbook.write', 'Write manager logbook notes'),
('document.read', 'Read authorized documents'),
('document.manage', 'Manage documents and acknowledgments'),
('chat.write', 'Send team messages'),
('event.read', 'View events and BEOs'),
('event.manage', 'Manage events and BEOs'),
('sales.read', 'View sales snapshots'),
('report.operational', 'View operational reports'),
('report.financial', 'View cost, margin, and financial reports'),
('integration.manage', 'Connect external systems'),
('billing.manage', 'Manage subscription and billing'),
('settings.manage', 'Manage venue settings')
on conflict(key) do update set description=excluded.description;
-- role_permissions
insert into public.role_permissions(role_key,permission_key) values
('organization_owner', 'schedule.board'),
('organization_owner', 'schedule.create'),
('organization_owner', 'schedule.edit'),
('organization_owner', 'schedule.retract'),
('organization_owner', 'schedule.copy'),
('organization_owner', 'schedule.open'),
('organization_owner', 'schedule.requirements'),
('organization_owner', 'schedule.drop.review'),
('organization_owner', 'schedule.pickup.review'),
('organization_owner', 'schedule.swap.review'),
('organization_owner', 'schedule.assign'),
('organization_owner', 'schedule.override'),
('organization_owner', 'labor.read'),
('organization_owner', 'labor.wage.manage'),
('organization_owner', 'schedule.availability.edit'),
('organization_owner', 'schedule.availability.all'),
('organization_owner', 'schedule.timeoff.review'),
('organization_owner', 'schedule.templates'),
('organization_owner', 'schedule.report'),
('organization_owner', 'schedule.settings'),
('organization_owner', 'staff.manage'),
('organization_owner', 'staff.certify'),
('organization_owner', 'schedule.self'),
('organization_owner', 'schedule.marketplace'),
('organization_owner', 'org.read'),
('organization_owner', 'org.update'),
('organization_owner', 'venue.create'),
('organization_owner', 'venue.read'),
('organization_owner', 'venue.update'),
('organization_owner', 'membership.read'),
('organization_owner', 'membership.invite'),
('organization_owner', 'membership.approve'),
('organization_owner', 'membership.assign_role'),
('organization_owner', 'audit.read'),
('organization_owner', 'wine.catalog.read'),
('organization_owner', 'wine.catalog.write'),
('organization_owner', 'wine.count.execute'),
('organization_owner', 'wine.count.review'),
('organization_owner', 'wine.count.approve'),
('organization_owner', 'wine.movement.write'),
('organization_owner', 'wine.receive'),
('organization_owner', 'wine.purchase'),
('organization_owner', 'wine.cost.read'),
('organization_owner', 'wine.allocation.manage'),
('organization_owner', 'wine.list.publish'),
('organization_owner', 'reservation.read'),
('organization_owner', 'reservation.write'),
('organization_owner', 'reservation.seat'),
('organization_owner', 'floor.read'),
('organization_owner', 'floor.design'),
('organization_owner', 'guest.read'),
('organization_owner', 'guest.write'),
('organization_owner', 'schedule.read'),
('organization_owner', 'schedule.publish'),
('organization_owner', 'timeclock.self'),
('organization_owner', 'timeclock.manage'),
('organization_owner', 'checklist.execute'),
('organization_owner', 'checklist.manage'),
('organization_owner', 'logbook.write'),
('organization_owner', 'document.read'),
('organization_owner', 'document.manage'),
('organization_owner', 'chat.write'),
('organization_owner', 'event.read'),
('organization_owner', 'event.manage'),
('organization_owner', 'sales.read'),
('organization_owner', 'report.operational'),
('organization_owner', 'report.financial'),
('organization_owner', 'integration.manage'),
('organization_owner', 'billing.manage'),
('organization_owner', 'settings.manage'),
('venue_administrator', 'schedule.board'),
('venue_administrator', 'schedule.create'),
('venue_administrator', 'schedule.edit'),
('venue_administrator', 'schedule.retract'),
('venue_administrator', 'schedule.copy'),
('venue_administrator', 'schedule.open'),
('venue_administrator', 'schedule.requirements'),
('venue_administrator', 'schedule.drop.review'),
('venue_administrator', 'schedule.pickup.review'),
('venue_administrator', 'schedule.swap.review'),
('venue_administrator', 'schedule.assign'),
('venue_administrator', 'schedule.override'),
('venue_administrator', 'labor.read'),
('venue_administrator', 'labor.wage.manage'),
('venue_administrator', 'schedule.availability.edit'),
('venue_administrator', 'schedule.availability.all'),
('venue_administrator', 'schedule.timeoff.review'),
('venue_administrator', 'schedule.templates'),
('venue_administrator', 'schedule.report'),
('venue_administrator', 'schedule.settings'),
('venue_administrator', 'staff.manage'),
('venue_administrator', 'staff.certify'),
('venue_administrator', 'schedule.self'),
('venue_administrator', 'schedule.marketplace'),
('venue_administrator', 'org.read'),
('venue_administrator', 'venue.create'),
('venue_administrator', 'venue.read'),
('venue_administrator', 'venue.update'),
('venue_administrator', 'membership.read'),
('venue_administrator', 'membership.invite'),
('venue_administrator', 'membership.approve'),
('venue_administrator', 'membership.assign_role'),
('venue_administrator', 'audit.read'),
('venue_administrator', 'wine.catalog.read'),
('venue_administrator', 'wine.catalog.write'),
('venue_administrator', 'wine.count.execute'),
('venue_administrator', 'wine.count.review'),
('venue_administrator', 'wine.count.approve'),
('venue_administrator', 'wine.movement.write'),
('venue_administrator', 'wine.receive'),
('venue_administrator', 'wine.purchase'),
('venue_administrator', 'wine.cost.read'),
('venue_administrator', 'wine.allocation.manage'),
('venue_administrator', 'wine.list.publish'),
('venue_administrator', 'reservation.read'),
('venue_administrator', 'reservation.write'),
('venue_administrator', 'reservation.seat'),
('venue_administrator', 'floor.read'),
('venue_administrator', 'floor.design'),
('venue_administrator', 'guest.read'),
('venue_administrator', 'guest.write'),
('venue_administrator', 'schedule.read'),
('venue_administrator', 'schedule.publish'),
('venue_administrator', 'timeclock.self'),
('venue_administrator', 'timeclock.manage'),
('venue_administrator', 'checklist.execute'),
('venue_administrator', 'checklist.manage'),
('venue_administrator', 'logbook.write'),
('venue_administrator', 'document.read'),
('venue_administrator', 'document.manage'),
('venue_administrator', 'chat.write'),
('venue_administrator', 'event.read'),
('venue_administrator', 'event.manage'),
('venue_administrator', 'sales.read'),
('venue_administrator', 'report.operational'),
('venue_administrator', 'report.financial'),
('venue_administrator', 'integration.manage'),
('venue_administrator', 'settings.manage'),
('general_manager', 'org.read'),
('general_manager', 'venue.read'),
('general_manager', 'venue.update'),
('general_manager', 'membership.read'),
('general_manager', 'membership.invite'),
('general_manager', 'membership.approve'),
('general_manager', 'audit.read'),
('general_manager', 'wine.catalog.read'),
('general_manager', 'wine.catalog.write'),
('general_manager', 'wine.count.execute'),
('general_manager', 'wine.count.review'),
('general_manager', 'wine.count.approve'),
('general_manager', 'wine.movement.write'),
('general_manager', 'wine.receive'),
('general_manager', 'wine.purchase'),
('general_manager', 'wine.cost.read'),
('general_manager', 'wine.allocation.manage'),
('general_manager', 'wine.list.publish'),
('general_manager', 'reservation.read'),
('general_manager', 'reservation.write'),
('general_manager', 'reservation.seat'),
('general_manager', 'floor.read'),
('general_manager', 'floor.design'),
('general_manager', 'guest.read'),
('general_manager', 'guest.write'),
('general_manager', 'schedule.read'),
('general_manager', 'schedule.publish'),
('general_manager', 'timeclock.self'),
('general_manager', 'timeclock.manage'),
('general_manager', 'checklist.execute'),
('general_manager', 'checklist.manage'),
('general_manager', 'logbook.write'),
('general_manager', 'document.read'),
('general_manager', 'document.manage'),
('general_manager', 'chat.write'),
('general_manager', 'event.read'),
('general_manager', 'event.manage'),
('general_manager', 'sales.read'),
('general_manager', 'report.operational'),
('general_manager', 'report.financial'),
('general_manager', 'settings.manage'),
('general_manager', 'schedule.self'),
('general_manager', 'schedule.marketplace'),
('general_manager', 'schedule.board'),
('general_manager', 'schedule.create'),
('general_manager', 'schedule.edit'),
('general_manager', 'schedule.retract'),
('general_manager', 'schedule.copy'),
('general_manager', 'schedule.open'),
('general_manager', 'schedule.requirements'),
('general_manager', 'schedule.drop.review'),
('general_manager', 'schedule.pickup.review'),
('general_manager', 'schedule.swap.review'),
('general_manager', 'schedule.assign'),
('general_manager', 'schedule.availability.edit'),
('general_manager', 'schedule.availability.all'),
('general_manager', 'schedule.timeoff.review'),
('general_manager', 'schedule.templates'),
('general_manager', 'schedule.report'),
('general_manager', 'schedule.override'),
('general_manager', 'labor.read'),
('general_manager', 'labor.wage.manage'),
('general_manager', 'schedule.settings'),
('general_manager', 'staff.manage'),
('general_manager', 'staff.certify'),
('beverage_director', 'org.read'),
('beverage_director', 'venue.read'),
('beverage_director', 'membership.read'),
('beverage_director', 'wine.catalog.read'),
('beverage_director', 'wine.catalog.write'),
('beverage_director', 'wine.count.execute'),
('beverage_director', 'wine.count.review'),
('beverage_director', 'wine.count.approve'),
('beverage_director', 'wine.movement.write'),
('beverage_director', 'wine.receive'),
('beverage_director', 'wine.purchase'),
('beverage_director', 'wine.cost.read'),
('beverage_director', 'wine.allocation.manage'),
('beverage_director', 'wine.list.publish'),
('beverage_director', 'reservation.read'),
('beverage_director', 'guest.read'),
('beverage_director', 'floor.read'),
('beverage_director', 'document.read'),
('beverage_director', 'chat.write'),
('beverage_director', 'event.read'),
('beverage_director', 'checklist.execute'),
('beverage_director', 'logbook.write'),
('beverage_director', 'timeclock.self'),
('beverage_director', 'report.operational'),
('beverage_director', 'report.financial'),
('beverage_director', 'schedule.self'),
('beverage_director', 'schedule.marketplace'),
('beverage_director', 'schedule.board'),
('beverage_director', 'schedule.create'),
('beverage_director', 'schedule.edit'),
('beverage_director', 'schedule.retract'),
('beverage_director', 'schedule.copy'),
('beverage_director', 'schedule.open'),
('beverage_director', 'schedule.requirements'),
('beverage_director', 'schedule.drop.review'),
('beverage_director', 'schedule.pickup.review'),
('beverage_director', 'schedule.swap.review'),
('beverage_director', 'schedule.assign'),
('beverage_director', 'schedule.availability.edit'),
('beverage_director', 'schedule.availability.all'),
('beverage_director', 'schedule.timeoff.review'),
('beverage_director', 'schedule.templates'),
('beverage_director', 'schedule.report'),
('event_manager', 'org.read'),
('event_manager', 'venue.read'),
('event_manager', 'membership.read'),
('event_manager', 'wine.catalog.read'),
('event_manager', 'wine.movement.write'),
('event_manager', 'reservation.read'),
('event_manager', 'reservation.write'),
('event_manager', 'floor.read'),
('event_manager', 'guest.read'),
('event_manager', 'guest.write'),
('event_manager', 'event.read'),
('event_manager', 'event.manage'),
('event_manager', 'document.read'),
('event_manager', 'document.manage'),
('event_manager', 'chat.write'),
('event_manager', 'checklist.execute'),
('event_manager', 'checklist.manage'),
('event_manager', 'logbook.write'),
('event_manager', 'schedule.read'),
('event_manager', 'report.operational'),
('event_manager', 'timeclock.self'),
('event_manager', 'schedule.self'),
('event_manager', 'schedule.marketplace'),
('event_manager', 'schedule.board'),
('event_manager', 'schedule.create'),
('event_manager', 'schedule.edit'),
('event_manager', 'schedule.retract'),
('event_manager', 'schedule.copy'),
('event_manager', 'schedule.open'),
('event_manager', 'schedule.requirements'),
('event_manager', 'schedule.drop.review'),
('event_manager', 'schedule.pickup.review'),
('event_manager', 'schedule.swap.review'),
('event_manager', 'schedule.assign'),
('event_manager', 'schedule.availability.edit'),
('event_manager', 'schedule.availability.all'),
('event_manager', 'schedule.timeoff.review'),
('event_manager', 'schedule.templates'),
('event_manager', 'schedule.report'),
('floor_manager', 'org.read'),
('floor_manager', 'venue.read'),
('floor_manager', 'reservation.read'),
('floor_manager', 'reservation.write'),
('floor_manager', 'reservation.seat'),
('floor_manager', 'floor.read'),
('floor_manager', 'floor.design'),
('floor_manager', 'guest.read'),
('floor_manager', 'guest.write'),
('floor_manager', 'schedule.read'),
('floor_manager', 'chat.write'),
('floor_manager', 'checklist.execute'),
('floor_manager', 'checklist.manage'),
('floor_manager', 'logbook.write'),
('floor_manager', 'document.read'),
('floor_manager', 'event.read'),
('floor_manager', 'wine.catalog.read'),
('floor_manager', 'timeclock.self'),
('floor_manager', 'timeclock.manage'),
('floor_manager', 'report.operational'),
('floor_manager', 'schedule.self'),
('floor_manager', 'schedule.marketplace'),
('floor_manager', 'schedule.board'),
('floor_manager', 'schedule.create'),
('floor_manager', 'schedule.edit'),
('floor_manager', 'schedule.retract'),
('floor_manager', 'schedule.copy'),
('floor_manager', 'schedule.open'),
('floor_manager', 'schedule.requirements'),
('floor_manager', 'schedule.drop.review'),
('floor_manager', 'schedule.pickup.review'),
('floor_manager', 'schedule.swap.review'),
('floor_manager', 'schedule.assign'),
('floor_manager', 'schedule.availability.edit'),
('floor_manager', 'schedule.availability.all'),
('floor_manager', 'schedule.timeoff.review'),
('floor_manager', 'schedule.templates'),
('floor_manager', 'schedule.report'),
('scheduler', 'org.read'),
('scheduler', 'venue.read'),
('scheduler', 'membership.read'),
('scheduler', 'schedule.read'),
('scheduler', 'schedule.publish'),
('scheduler', 'timeclock.manage'),
('scheduler', 'timeclock.self'),
('scheduler', 'document.read'),
('scheduler', 'chat.write'),
('scheduler', 'report.operational'),
('scheduler', 'schedule.self'),
('scheduler', 'schedule.marketplace'),
('scheduler', 'schedule.board'),
('scheduler', 'schedule.create'),
('scheduler', 'schedule.edit'),
('scheduler', 'schedule.retract'),
('scheduler', 'schedule.copy'),
('scheduler', 'schedule.open'),
('scheduler', 'schedule.requirements'),
('scheduler', 'schedule.drop.review'),
('scheduler', 'schedule.pickup.review'),
('scheduler', 'schedule.swap.review'),
('scheduler', 'schedule.assign'),
('scheduler', 'schedule.availability.edit'),
('scheduler', 'schedule.availability.all'),
('scheduler', 'schedule.timeoff.review'),
('scheduler', 'schedule.templates'),
('scheduler', 'schedule.report'),
('scheduler', 'schedule.override'),
('scheduler', 'labor.read'),
('scheduler', 'labor.wage.manage'),
('scheduler', 'schedule.settings'),
('scheduler', 'staff.manage'),
('scheduler', 'staff.certify'),
('department_manager', 'org.read'),
('department_manager', 'venue.read'),
('department_manager', 'schedule.self'),
('department_manager', 'schedule.marketplace'),
('department_manager', 'timeclock.self'),
('department_manager', 'chat.write'),
('department_manager', 'document.read'),
('department_manager', 'schedule.board'),
('department_manager', 'schedule.create'),
('department_manager', 'schedule.edit'),
('department_manager', 'schedule.retract'),
('department_manager', 'schedule.copy'),
('department_manager', 'schedule.open'),
('department_manager', 'schedule.requirements'),
('department_manager', 'schedule.drop.review'),
('department_manager', 'schedule.pickup.review'),
('department_manager', 'schedule.swap.review'),
('department_manager', 'schedule.assign'),
('department_manager', 'schedule.availability.edit'),
('department_manager', 'schedule.availability.all'),
('department_manager', 'schedule.timeoff.review'),
('department_manager', 'schedule.templates'),
('department_manager', 'schedule.report'),
('department_manager', 'schedule.override'),
('shift_lead', 'org.read'),
('shift_lead', 'venue.read'),
('shift_lead', 'schedule.self'),
('shift_lead', 'schedule.marketplace'),
('shift_lead', 'timeclock.self'),
('shift_lead', 'chat.write'),
('shift_lead', 'document.read'),
('shift_lead', 'schedule.board'),
('shift_lead', 'schedule.report'),
('employee', 'org.read'),
('employee', 'venue.read'),
('employee', 'schedule.self'),
('employee', 'schedule.marketplace'),
('employee', 'timeclock.self'),
('employee', 'chat.write'),
('employee', 'document.read'),
('host', 'org.read'),
('host', 'venue.read'),
('host', 'reservation.read'),
('host', 'reservation.write'),
('host', 'reservation.seat'),
('host', 'floor.read'),
('host', 'guest.read'),
('host', 'guest.write'),
('host', 'chat.write'),
('host', 'document.read'),
('host', 'wine.catalog.read'),
('host', 'timeclock.self'),
('host', 'event.read'),
('host', 'schedule.self'),
('host', 'schedule.marketplace'),
('bartender', 'org.read'),
('bartender', 'venue.read'),
('bartender', 'wine.catalog.read'),
('bartender', 'wine.count.execute'),
('bartender', 'wine.movement.write'),
('bartender', 'chat.write'),
('bartender', 'checklist.execute'),
('bartender', 'timeclock.self'),
('bartender', 'document.read'),
('bartender', 'floor.read'),
('bartender', 'schedule.self'),
('bartender', 'schedule.marketplace'),
('server', 'org.read'),
('server', 'venue.read'),
('server', 'reservation.read'),
('server', 'floor.read'),
('server', 'guest.read'),
('server', 'chat.write'),
('server', 'checklist.execute'),
('server', 'wine.catalog.read'),
('server', 'timeclock.self'),
('server', 'document.read'),
('server', 'schedule.self'),
('server', 'schedule.marketplace'),
('inventory_counter', 'org.read'),
('inventory_counter', 'venue.read'),
('inventory_counter', 'wine.catalog.read'),
('inventory_counter', 'wine.count.execute'),
('inventory_counter', 'checklist.execute'),
('inventory_counter', 'timeclock.self'),
('inventory_counter', 'document.read'),
('inventory_counter', 'schedule.self'),
('inventory_counter', 'schedule.marketplace'),
('inventory_counter', 'chat.write'),
('auditor', 'org.read'),
('auditor', 'venue.read'),
('auditor', 'membership.read'),
('auditor', 'audit.read'),
('auditor', 'wine.catalog.read'),
('auditor', 'wine.cost.read'),
('auditor', 'reservation.read'),
('auditor', 'floor.read'),
('auditor', 'guest.read'),
('auditor', 'schedule.read'),
('auditor', 'document.read'),
('auditor', 'event.read'),
('auditor', 'sales.read'),
('auditor', 'report.operational'),
('auditor', 'report.financial'),
('auditor', 'schedule.board'),
('auditor', 'schedule.report'),
('auditor', 'labor.read')
on conflict do nothing;
