import 'permission.dart';
import 'app_role.dart';

abstract final class RoleCatalog {
  static const _wineOps = <String>[
    Permission.wineCatalogRead,
    Permission.wineCatalogWrite,
    Permission.wineCountExecute,
    Permission.wineCountReview,
    Permission.wineCountApprove,
    Permission.wineMovementWrite,
    Permission.wineReceive,
    Permission.winePurchase,
    Permission.wineCostRead,
    Permission.wineAllocationManage,
    Permission.wineListPublish,
  ];

  static final Map<AppRole, Set<String>> grants = {
    AppRole.organizationOwner: Permission.all.toSet(),
    AppRole.venueAdministrator: Permission.all
        .where(
          (permission) =>
              permission != Permission.billingManage &&
              permission != Permission.orgUpdate,
        )
        .toSet(),
    AppRole.generalManager: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.venueUpdate,
      Permission.membershipRead,
      Permission.membershipInvite,
      Permission.membershipApprove,
      Permission.auditRead,
      ..._wineOps,
      Permission.reservationRead,
      Permission.reservationWrite,
      Permission.reservationSeat,
      Permission.floorRead,
      Permission.floorDesign,
      Permission.guestRead,
      Permission.guestWrite,
      Permission.scheduleRead,
      Permission.schedulePublish,
      Permission.timeclockSelf,
      Permission.timeclockManage,
      Permission.checklistExecute,
      Permission.checklistManage,
      Permission.logbookWrite,
      Permission.documentRead,
      Permission.documentManage,
      Permission.chatWrite,
      Permission.eventRead,
      Permission.eventManage,
      Permission.salesRead,
      Permission.reportOperational,
      Permission.reportFinancial,
      Permission.settingsManage,
    },
    AppRole.beverageDirector: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.membershipRead,
      ..._wineOps,
      Permission.reservationRead,
      Permission.guestRead,
      Permission.floorRead,
      Permission.documentRead,
      Permission.chatWrite,
      Permission.eventRead,
      Permission.checklistExecute,
      Permission.logbookWrite,
      Permission.timeclockSelf,
      Permission.reportOperational,
      Permission.reportFinancial,
    },
    AppRole.eventManager: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.membershipRead,
      Permission.wineCatalogRead,
      Permission.wineMovementWrite,
      Permission.reservationRead,
      Permission.reservationWrite,
      Permission.floorRead,
      Permission.guestRead,
      Permission.guestWrite,
      Permission.eventRead,
      Permission.eventManage,
      Permission.documentRead,
      Permission.documentManage,
      Permission.chatWrite,
      Permission.checklistExecute,
      Permission.checklistManage,
      Permission.logbookWrite,
      Permission.scheduleRead,
      Permission.reportOperational,
      Permission.timeclockSelf,
    },
    AppRole.floorManager: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.reservationRead,
      Permission.reservationWrite,
      Permission.reservationSeat,
      Permission.floorRead,
      Permission.floorDesign,
      Permission.guestRead,
      Permission.guestWrite,
      Permission.scheduleRead,
      Permission.chatWrite,
      Permission.checklistExecute,
      Permission.checklistManage,
      Permission.logbookWrite,
      Permission.documentRead,
      Permission.eventRead,
      Permission.wineCatalogRead,
      Permission.timeclockSelf,
      Permission.timeclockManage,
      Permission.reportOperational,
    },
    AppRole.host: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.reservationRead,
      Permission.reservationWrite,
      Permission.reservationSeat,
      Permission.floorRead,
      Permission.guestRead,
      Permission.guestWrite,
      Permission.chatWrite,
      Permission.documentRead,
      Permission.wineCatalogRead,
      Permission.timeclockSelf,
      Permission.eventRead,
    },
    AppRole.server: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.reservationRead,
      Permission.floorRead,
      Permission.guestRead,
      Permission.chatWrite,
      Permission.checklistExecute,
      Permission.wineCatalogRead,
      Permission.timeclockSelf,
      Permission.documentRead,
    },
    AppRole.bartender: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.wineCatalogRead,
      Permission.wineCountExecute,
      Permission.wineMovementWrite,
      Permission.chatWrite,
      Permission.checklistExecute,
      Permission.timeclockSelf,
      Permission.documentRead,
      Permission.floorRead,
    },
    AppRole.inventoryCounter: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.wineCatalogRead,
      Permission.wineCountExecute,
      Permission.checklistExecute,
      Permission.timeclockSelf,
      Permission.documentRead,
    },
    AppRole.scheduler: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.membershipRead,
      Permission.scheduleRead,
      Permission.schedulePublish,
      Permission.timeclockManage,
      Permission.timeclockSelf,
      Permission.documentRead,
      Permission.chatWrite,
      Permission.reportOperational,
    },
    AppRole.auditor: {
      Permission.orgRead,
      Permission.venueRead,
      Permission.membershipRead,
      Permission.auditRead,
      Permission.wineCatalogRead,
      Permission.wineCostRead,
      Permission.reservationRead,
      Permission.floorRead,
      Permission.guestRead,
      Permission.scheduleRead,
      Permission.documentRead,
      Permission.eventRead,
      Permission.salesRead,
      Permission.reportOperational,
      Permission.reportFinancial,
    },
  };

  static Set<String> permissionsFor(AppRole role) {
    return Set.unmodifiable(grants[role] ?? const {});
  }

  static bool roleHas(AppRole role, String permission) {
    return grants[role]?.contains(permission) ?? false;
  }
}
