-- app_roles
insert into public.app_roles (key, label, rank) values
  ('organization_owner', 'Organization owner', 10),
  ('venue_administrator', 'Venue administrator', 20),
  ('general_manager', 'General manager', 30),
  ('beverage_director', 'Beverage director', 40),
  ('event_manager', 'Event manager', 40),
  ('floor_manager', 'Floor manager', 50),
  ('scheduler', 'Scheduler', 50),
  ('host', 'Host', 60),
  ('bartender', 'Bartender', 60),
  ('server', 'Server', 70),
  ('inventory_counter', 'Inventory counter', 70),
  ('auditor', 'Read-only auditor', 120)
on conflict (key) do update set label = excluded.label, rank = excluded.rank;
-- permissions
insert into public.permissions (key, description) values
  ('org.read', 'View the organization profile'),
  ('org.update', 'Update organization identity'),
  ('venue.create', 'Create a venue'),
  ('venue.read', 'View venue profile and hours'),
  ('venue.update', 'Update venue settings'),
  ('membership.read', 'View team memberships'),
  ('membership.invite', 'Invite a person to the organization'),
  ('membership.approve', 'Approve or decline a join request'),
  ('membership.assign_role', 'Change an existing membership role'),
  ('audit.read', 'Read the audit log'),
  ('wine.catalog.read', 'View the wine catalog'),
  ('wine.catalog.write', 'Edit wine master data'),
  ('wine.count.execute', 'Enter inventory counts'),
  ('wine.count.review', 'Review count variances'),
  ('wine.count.approve', 'Approve count adjustments'),
  ('wine.movement.write', 'Move or transfer inventory'),
  ('wine.receive', 'Receive purchase orders'),
  ('wine.purchase', 'Create purchase orders and manage vendors'),
  ('wine.cost.read', 'View unit cost and valuation'),
  ('wine.allocation.manage', 'Manage club allocations and member holdings'),
  ('wine.list.publish', 'Publish wine list availability'),
  ('reservation.read', 'View reservations'),
  ('reservation.write', 'Create and edit reservations'),
  ('reservation.seat', 'Seat, waitlist, and complete covers'),
  ('floor.read', 'View the live floor'),
  ('floor.design', 'Edit floor layouts'),
  ('guest.read', 'View guest profiles'),
  ('guest.write', 'Edit guest profiles and notes'),
  ('schedule.read', 'View the published schedule'),
  ('schedule.publish', 'Publish schedules'),
  ('timeclock.self', 'Clock in and out for yourself'),
  ('timeclock.manage', 'Review and correct time entries'),
  ('checklist.execute', 'Complete assigned checklist items'),
  ('checklist.manage', 'Manage checklist templates and signoff'),
  ('logbook.write', 'Write manager logbook notes'),
  ('document.read', 'Read authorized documents'),
  ('document.manage', 'Manage documents and acknowledgments'),
  ('chat.write', 'Send team messages'),
  ('event.read', 'View events and BEOs'),
  ('event.manage', 'Manage events and BEOs'),
  ('sales.read', 'View sales snapshots'),
  ('report.operational', 'View operational reports'),
  ('report.financial', 'View cost, margin, and financial reports'),
  ('integration.manage', 'Connect external systems'),
  ('billing.manage', 'Manage subscription and billing'),
  ('settings.manage', 'Manage venue settings')
on conflict (key) do update set description = excluded.description;
-- role_permissions
insert into public.role_permissions (role_key, permission_key) values
  ('organization_owner', 'audit.read'),
  ('organization_owner', 'billing.manage'),
  ('organization_owner', 'chat.write'),
  ('organization_owner', 'checklist.execute'),
  ('organization_owner', 'checklist.manage'),
  ('organization_owner', 'document.manage'),
  ('organization_owner', 'document.read'),
  ('organization_owner', 'event.manage'),
  ('organization_owner', 'event.read'),
  ('organization_owner', 'floor.design'),
  ('organization_owner', 'floor.read'),
  ('organization_owner', 'guest.read'),
  ('organization_owner', 'guest.write'),
  ('organization_owner', 'integration.manage'),
  ('organization_owner', 'logbook.write'),
  ('organization_owner', 'membership.approve'),
  ('organization_owner', 'membership.assign_role'),
  ('organization_owner', 'membership.invite'),
  ('organization_owner', 'membership.read'),
  ('organization_owner', 'org.read'),
  ('organization_owner', 'org.update'),
  ('organization_owner', 'report.financial'),
  ('organization_owner', 'report.operational'),
  ('organization_owner', 'reservation.read'),
  ('organization_owner', 'reservation.seat'),
  ('organization_owner', 'reservation.write'),
  ('organization_owner', 'sales.read'),
  ('organization_owner', 'schedule.publish'),
  ('organization_owner', 'schedule.read'),
  ('organization_owner', 'settings.manage'),
  ('organization_owner', 'timeclock.manage'),
  ('organization_owner', 'timeclock.self'),
  ('organization_owner', 'venue.create'),
  ('organization_owner', 'venue.read'),
  ('organization_owner', 'venue.update'),
  ('organization_owner', 'wine.allocation.manage'),
  ('organization_owner', 'wine.catalog.read'),
  ('organization_owner', 'wine.catalog.write'),
  ('organization_owner', 'wine.cost.read'),
  ('organization_owner', 'wine.count.approve'),
  ('organization_owner', 'wine.count.execute'),
  ('organization_owner', 'wine.count.review'),
  ('organization_owner', 'wine.list.publish'),
  ('organization_owner', 'wine.movement.write'),
  ('organization_owner', 'wine.purchase'),
  ('organization_owner', 'wine.receive'),
  ('venue_administrator', 'audit.read'),
  ('venue_administrator', 'chat.write'),
  ('venue_administrator', 'checklist.execute'),
  ('venue_administrator', 'checklist.manage'),
  ('venue_administrator', 'document.manage'),
  ('venue_administrator', 'document.read'),
  ('venue_administrator', 'event.manage'),
  ('venue_administrator', 'event.read'),
  ('venue_administrator', 'floor.design'),
  ('venue_administrator', 'floor.read'),
  ('venue_administrator', 'guest.read'),
  ('venue_administrator', 'guest.write'),
  ('venue_administrator', 'integration.manage'),
  ('venue_administrator', 'logbook.write'),
  ('venue_administrator', 'membership.approve'),
  ('venue_administrator', 'membership.assign_role'),
  ('venue_administrator', 'membership.invite'),
  ('venue_administrator', 'membership.read'),
  ('venue_administrator', 'org.read'),
  ('venue_administrator', 'report.financial'),
  ('venue_administrator', 'report.operational'),
  ('venue_administrator', 'reservation.read'),
  ('venue_administrator', 'reservation.seat'),
  ('venue_administrator', 'reservation.write'),
  ('venue_administrator', 'sales.read'),
  ('venue_administrator', 'schedule.publish'),
  ('venue_administrator', 'schedule.read'),
  ('venue_administrator', 'settings.manage'),
  ('venue_administrator', 'timeclock.manage'),
  ('venue_administrator', 'timeclock.self'),
  ('venue_administrator', 'venue.create'),
  ('venue_administrator', 'venue.read'),
  ('venue_administrator', 'venue.update'),
  ('venue_administrator', 'wine.allocation.manage'),
  ('venue_administrator', 'wine.catalog.read'),
  ('venue_administrator', 'wine.catalog.write'),
  ('venue_administrator', 'wine.cost.read'),
  ('venue_administrator', 'wine.count.approve'),
  ('venue_administrator', 'wine.count.execute'),
  ('venue_administrator', 'wine.count.review'),
  ('venue_administrator', 'wine.list.publish'),
  ('venue_administrator', 'wine.movement.write'),
  ('venue_administrator', 'wine.purchase'),
  ('venue_administrator', 'wine.receive'),
  ('general_manager', 'audit.read'),
  ('general_manager', 'chat.write'),
  ('general_manager', 'checklist.execute'),
  ('general_manager', 'checklist.manage'),
  ('general_manager', 'document.manage'),
  ('general_manager', 'document.read'),
  ('general_manager', 'event.manage'),
  ('general_manager', 'event.read'),
  ('general_manager', 'floor.design'),
  ('general_manager', 'floor.read'),
  ('general_manager', 'guest.read'),
  ('general_manager', 'guest.write'),
  ('general_manager', 'logbook.write'),
  ('general_manager', 'membership.approve'),
  ('general_manager', 'membership.invite'),
  ('general_manager', 'membership.read'),
  ('general_manager', 'org.read'),
  ('general_manager', 'report.financial'),
  ('general_manager', 'report.operational'),
  ('general_manager', 'reservation.read'),
  ('general_manager', 'reservation.seat'),
  ('general_manager', 'reservation.write'),
  ('general_manager', 'sales.read'),
  ('general_manager', 'schedule.publish'),
  ('general_manager', 'schedule.read'),
  ('general_manager', 'settings.manage'),
  ('general_manager', 'timeclock.manage'),
  ('general_manager', 'timeclock.self'),
  ('general_manager', 'venue.read'),
  ('general_manager', 'venue.update'),
  ('general_manager', 'wine.allocation.manage'),
  ('general_manager', 'wine.catalog.read'),
  ('general_manager', 'wine.catalog.write'),
  ('general_manager', 'wine.cost.read'),
  ('general_manager', 'wine.count.approve'),
  ('general_manager', 'wine.count.execute'),
  ('general_manager', 'wine.count.review'),
  ('general_manager', 'wine.list.publish'),
  ('general_manager', 'wine.movement.write'),
  ('general_manager', 'wine.purchase'),
  ('general_manager', 'wine.receive'),
  ('beverage_director', 'chat.write'),
  ('beverage_director', 'checklist.execute'),
  ('beverage_director', 'document.read'),
  ('beverage_director', 'event.read'),
  ('beverage_director', 'floor.read'),
  ('beverage_director', 'guest.read'),
  ('beverage_director', 'logbook.write'),
  ('beverage_director', 'membership.read'),
  ('beverage_director', 'org.read'),
  ('beverage_director', 'report.financial'),
  ('beverage_director', 'report.operational'),
  ('beverage_director', 'reservation.read'),
  ('beverage_director', 'timeclock.self'),
  ('beverage_director', 'venue.read'),
  ('beverage_director', 'wine.allocation.manage'),
  ('beverage_director', 'wine.catalog.read'),
  ('beverage_director', 'wine.catalog.write'),
  ('beverage_director', 'wine.cost.read'),
  ('beverage_director', 'wine.count.approve'),
  ('beverage_director', 'wine.count.execute'),
  ('beverage_director', 'wine.count.review'),
  ('beverage_director', 'wine.list.publish'),
  ('beverage_director', 'wine.movement.write'),
  ('beverage_director', 'wine.purchase'),
  ('beverage_director', 'wine.receive'),
  ('event_manager', 'chat.write'),
  ('event_manager', 'checklist.execute'),
  ('event_manager', 'checklist.manage'),
  ('event_manager', 'document.manage'),
  ('event_manager', 'document.read'),
  ('event_manager', 'event.manage'),
  ('event_manager', 'event.read'),
  ('event_manager', 'floor.read'),
  ('event_manager', 'guest.read'),
  ('event_manager', 'guest.write'),
  ('event_manager', 'logbook.write'),
  ('event_manager', 'membership.read'),
  ('event_manager', 'org.read'),
  ('event_manager', 'report.operational'),
  ('event_manager', 'reservation.read'),
  ('event_manager', 'reservation.write'),
  ('event_manager', 'schedule.read'),
  ('event_manager', 'timeclock.self'),
  ('event_manager', 'venue.read'),
  ('event_manager', 'wine.catalog.read'),
  ('event_manager', 'wine.movement.write'),
  ('floor_manager', 'chat.write'),
  ('floor_manager', 'checklist.execute'),
  ('floor_manager', 'checklist.manage'),
  ('floor_manager', 'document.read'),
  ('floor_manager', 'event.read'),
  ('floor_manager', 'floor.design'),
  ('floor_manager', 'floor.read'),
  ('floor_manager', 'guest.read'),
  ('floor_manager', 'guest.write'),
  ('floor_manager', 'logbook.write'),
  ('floor_manager', 'org.read'),
  ('floor_manager', 'report.operational'),
  ('floor_manager', 'reservation.read'),
  ('floor_manager', 'reservation.seat'),
  ('floor_manager', 'reservation.write'),
  ('floor_manager', 'schedule.read'),
  ('floor_manager', 'timeclock.manage'),
  ('floor_manager', 'timeclock.self'),
  ('floor_manager', 'venue.read'),
  ('floor_manager', 'wine.catalog.read'),
  ('scheduler', 'chat.write'),
  ('scheduler', 'document.read'),
  ('scheduler', 'membership.read'),
  ('scheduler', 'org.read'),
  ('scheduler', 'report.operational'),
  ('scheduler', 'schedule.publish'),
  ('scheduler', 'schedule.read'),
  ('scheduler', 'timeclock.manage'),
  ('scheduler', 'timeclock.self'),
  ('scheduler', 'venue.read'),
  ('host', 'chat.write'),
  ('host', 'document.read'),
  ('host', 'event.read'),
  ('host', 'floor.read'),
  ('host', 'guest.read'),
  ('host', 'guest.write'),
  ('host', 'org.read'),
  ('host', 'reservation.read'),
  ('host', 'reservation.seat'),
  ('host', 'reservation.write'),
  ('host', 'timeclock.self'),
  ('host', 'venue.read'),
  ('host', 'wine.catalog.read'),
  ('bartender', 'chat.write'),
  ('bartender', 'checklist.execute'),
  ('bartender', 'document.read'),
  ('bartender', 'floor.read'),
  ('bartender', 'org.read'),
  ('bartender', 'timeclock.self'),
  ('bartender', 'venue.read'),
  ('bartender', 'wine.catalog.read'),
  ('bartender', 'wine.count.execute'),
  ('bartender', 'wine.movement.write'),
  ('server', 'chat.write'),
  ('server', 'checklist.execute'),
  ('server', 'document.read'),
  ('server', 'floor.read'),
  ('server', 'guest.read'),
  ('server', 'org.read'),
  ('server', 'reservation.read'),
  ('server', 'timeclock.self'),
  ('server', 'venue.read'),
  ('server', 'wine.catalog.read'),
  ('inventory_counter', 'checklist.execute'),
  ('inventory_counter', 'document.read'),
  ('inventory_counter', 'org.read'),
  ('inventory_counter', 'timeclock.self'),
  ('inventory_counter', 'venue.read'),
  ('inventory_counter', 'wine.catalog.read'),
  ('inventory_counter', 'wine.count.execute'),
  ('auditor', 'audit.read'),
  ('auditor', 'document.read'),
  ('auditor', 'event.read'),
  ('auditor', 'floor.read'),
  ('auditor', 'guest.read'),
  ('auditor', 'membership.read'),
  ('auditor', 'org.read'),
  ('auditor', 'report.financial'),
  ('auditor', 'report.operational'),
  ('auditor', 'reservation.read'),
  ('auditor', 'sales.read'),
  ('auditor', 'schedule.read'),
  ('auditor', 'venue.read'),
  ('auditor', 'wine.catalog.read'),
  ('auditor', 'wine.cost.read')
on conflict do nothing;
